### ISSUE TITLE
Confidence for the given image

### ISSUE THREAD

**Issue by deepakraina99** [aL3x-O-o-Hung/ultrasound-conidence-map-with-directed-graphs#1]
Can you try measuring the confidence for the attached ultrasound image?
![2_edit](https://user-images.githubusercontent.com/34967469/151272129-a41818ce-e181-4ef6-815f-c65cb73a0330.jpg)
?

I am getting the following error:
```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    ref=confidence_map(ref)
  File "$HOME/ultrasound-confidence-map-with-directed-graphs/confidence_with_dg.py", line 48, in confidence_map
    filted_image=ESRAD_filter.Execute(image)
  File "$HOME/ultrasound-confidence-map-with-directed-graphs/EdgeHistogramSRAD.py", line 135, in Execute
    roi_seg[x, y] = 1
  File "$HOME/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 4276, in __setitem__
    raise IndexError("index {0} is outside the extent for dimension {1} with size {2}".format( idx[i], i, size[i]))
IndexError: index 300 is outside the extent for dimension 1 with size 200
```

**Comment by aL3x-O-o-Hung** [comment]
Hi!

Thanks for the interest in our project! The input to the algorithm must be
a grayscale image. I think that is why you are getting the error. That
being said, the current code does not really support non-linear images (fan
shape images), so even if you are able to run the code, the result would
not be so good. The way to calculate the confidence on fan shape images is
that you need straighten the top part and set the confidence in the
non-ultrasound regions to 0. Please let me know if you have any questions.
By the way, what is the purpose of this? I might be able to help with the
code for fan shape images, but I probably would not have time recently.

Thanks
Alex

**Comment by aL3x-O-o-Hung** [comment]
Hi,

Sorry I was thinking about something else earlier. You can calculate the
confidence without straightening the curve. However, you need to hard code
the top of the image so that the confidence values of those pixels are 1.
Please let me know if you have any questions

Thanks
Alex

**Comment by deepakraina99** [comment]
Hi, thanks for your response. Yes I could understand that it requires a 2d image. But it still gives error with 2d image too.

**Comment by deepakraina99** [comment]
By 2d, I mean grayscale image.

**Comment by deepakraina99** [comment]
Plus I can always crop it to region of interest so that it will be rectangular shaped image.

**Comment by aL3x-O-o-Hung** [comment]
Did you normalize the image to [0,1]? I have no problem running the code on my end.

**Comment by deepakraina99** [comment]
Yes, it works fine now. That's a pretty amazing work. Thanks for sharing the code. 

I have few other things to discuss in relation to this algorithm, but I would like to have this conversation over your email.

**Comment by aL3x-O-o-Hung** [comment]
Sure, just shoot me an email @***@***.*** and we can discuss.
